import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { StatusPill } from "@/components/StatusPill";
import { MockBadge } from "@/components/MockBadge";
import { currentUser, usePact } from "@/lib/store";
import { getMonthStatus, leaseMonths } from "@/lib/reporting";
import { currentMonth, formatDate, formatMoney, monthLabel } from "@/lib/format";

const History = () => {
  const db = usePact();
  const user = currentUser(db)!;
  const lease = db.leases.find((l) => l.tenantId === user.id);
  if (!lease) return <p className="text-sm">Add your rental details first.</p>;

  const months = leaseMonths(lease, currentMonth()).map((m) => getMonthStatus(db, lease, m));

  return (
    <div className="space-y-5">
      <div>
        <h1 className="font-display text-2xl">Reporting history</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Every month since your rental started, and exactly what happened with it.
        </p>
      </div>

      <Accordion type="single" collapsible className="space-y-2">
        {months.map((m) => (
          <AccordionItem
            key={m.month}
            value={m.month}
            className="rounded-2xl border bg-card px-4"
          >
            <AccordionTrigger className="hover:no-underline">
              <div className="flex w-full items-center justify-between gap-3 pr-2">
                <div className="text-left">
                  <p className="text-sm font-semibold">{monthLabel(m.month)}</p>
                  <p className="text-xs text-muted-foreground">
                    {m.methodLabel ?? "Not verified"}
                  </p>
                </div>
                <StatusPill state={m.state} label={m.label} />
              </div>
            </AccordionTrigger>
            <AccordionContent className="space-y-3 pb-4 text-sm">
              <p className="leading-relaxed text-muted-foreground">{m.explanation}</p>
              {m.payment && (
                <dl className="grid grid-cols-2 gap-2 rounded-2xl bg-muted/60 p-3 text-xs">
                  <div>
                    <dt className="text-muted-foreground">Amount</dt>
                    <dd className="font-semibold">
                      {formatMoney(m.payment.amount, m.payment.currency)}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Paid on</dt>
                    <dd className="font-semibold">{formatDate(m.payment.paidOn)}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">How it was verified</dt>
                    <dd className="font-semibold">{m.methodLabel}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Source</dt>
                    <dd className="font-semibold">{m.payment.source}</dd>
                  </div>
                  {m.payment.proofFileName && (
                    <div className="col-span-2">
                      <dt className="text-muted-foreground">Attached proof</dt>
                      <dd className="font-semibold">{m.payment.proofFileName}</dd>
                    </div>
                  )}
                  {m.report && (
                    <div className="col-span-2">
                      <dt className="text-muted-foreground">Sent to</dt>
                      <dd className="font-semibold">
                        {m.report.partnerName}
                        {m.report.partnerRef ? ` · ref ${m.report.partnerRef}` : ""}
                      </dd>
                    </div>
                  )}
                </dl>
              )}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <MockBadge>
        Partner reference numbers here are generated by the sandbox reporting partner.
      </MockBadge>
    </div>
  );
};

export default History;