// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://tjaxqguzkczllkurpthp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "sb_publishable_xEjh1HLWZQdoY1P6fZwHjQ_J7U9VhXK";

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);